import { expect, test } from '@playwright/test'

test('project rules require acceptance and retain cabinet overrides', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: '+ Board' })).toBeEnabled({ timeout: 120_000 })
  await page.getByLabel('Add cabinet').click()
  await page.getByRole('option', { name: 'Base 600' }).click()
  const cabinet = page.locator('[data-testid^="node-cmp_"]').filter({ hasText: 'Base 600' }).first()
  await cabinet.click()
  await page.getByLabel('Width', { exact: true }).fill('750')
  // Wait for the debounced item edit before opening the project specification.
  await page.getByText('Base 600 v1 · item overrides', { exact: true }).click()
  await expect(page.getByText('width: Item override', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'File', exact: true }).click()
  await page.getByRole('button', { name: 'Project structure…', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Project structure' })
  await dialog.getByLabel('Project Front reveal mm').fill('5')
  await dialog.getByRole('button', { name: 'Preview project rules' }).click()
  await expect(dialog.getByText(/1 cabinets affected/)).toBeVisible()
  await dialog.getByRole('button', { name: 'Apply project rules' }).click()
  await expect(dialog.getByRole('button', { name: 'Apply project rules' })).toHaveCount(0)
  await dialog.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.getByLabel('Width', { exact: true })).toHaveValue('750')
  await page.getByText('Base 600 v1 · item overrides', { exact: true }).click()
  await expect(page.getByText('Front reveal mm: Project', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Preview catalogue update' }).click()
  await expect(page.getByText('0 cabinets affected; 0 parts changed.', { exact: true })).toBeVisible()
})
